/** 九个角色的身份、工具权限与循环图唯一口径(契约 §9.55)。 */
import { BOT_ROLES, type BotRole } from './bots.js';

export type AgentChatState = 'idle' | 'queued' | 'thinking' | 'tool' | 'error';
export type LoopNodeKind = 'trigger' | 'read' | 'code' | 'model' | 'gate' | 'handoff' | 'output' | 'human';
export interface AgentGraph {
  entry: string;
  nodes: { id: string; label: string; kind: LoopNodeKind; to_role?: BotRole | null }[];
  edges: { from: string; to: string; label?: string | null }[];
}
export interface LoopSpec { cadence: string; affected_by_pause: boolean; graph: AgentGraph }
export interface AgentSpec { name: string; callsign: string; tagline: string; tools: string[]; skills: string[]; loop: LoopSpec }
export interface AgentTool { name: string; group: 'read' | 'research' | 'act' | 'config'; summary: string }
interface ToolSpec extends AgentTool { doc: string; owner: BotRole }
export const CHAT_TOOL_CATALOG: Record<string, ToolSpec> = {
  get_state: { name: "get_state", group: "read", owner: "gate_captain", summary: "账户、行情、工作流、队列、信息员最新总结。", doc: "get_state{}:账户、行情、工作流、队列、信息员最新总结。" },
  list_threads: { name: "list_threads", group: "read", owner: "thread_manager", summary: "策略线程列表。", doc: "list_threads{\"status\":\"open|all\"}:策略线程列表。" },
  get_thread: { name: "get_thread", group: "read", owner: "thread_manager", summary: "一条线程的细节、判断记录与活动流。", doc: "get_thread{\"id\":\"thr-…\"}:一条线程的细节、判断记录与活动流。" },
  get_episode: { name: "get_episode", group: "read", owner: "thread_manager", summary: "一条判断记录当时看到的证据(E1…En 原文)、输出的判断、代码闸结果——用户问\"为什么这样判断\"时用这个。", doc: "get_episode{\"id\":\"ep-…\"}:一条判断记录当时看到的证据(E1…En 原文)、输出的判断、代码闸结果——用户问\"为什么这样判断\"时用这个。" },
  list_history: { name: "list_history", group: "read", owner: "reviewer", summary: "已结束的交易(盈亏、R 倍数、持有时长、平仓原因)与统计(胜率、盈亏比、按币/来源分布)——用户要复盘时用。", doc: "list_history{\"limit\":20}:已结束的交易(盈亏、R 倍数、持有时长、平仓原因)与统计(胜率、盈亏比、按币/来源分布)——用户要复盘时用。" },
  propose_thread: { name: "propose_thread", group: "act", owner: "thread_manager", summary: "提议一条线程;数量由代码算,会过同样的闸;工作流关了自动执行时会等用户在界面确认。", doc: "propose_thread{\"symbol\":\"BTCUSDT\",\"side\":\"long|short\",\"entry\":\"market|limit\",\"limit_price\":\"…或null\",\"stop_price\":\"…\",\"take_profits\":[\"…\"],\"thesis\":\"一句话\"}:提议一条线程;数量由代码算,会过同样的闸;工作流关了自动执行时会等用户在界面确认。" },
  close_thread: { name: "close_thread", group: "act", owner: "thread_manager", summary: "平掉/撤掉一条线程(市价)。", doc: "close_thread{\"id\":\"thr-…\"}:平掉/撤掉一条线程(市价)。" },
  set_workflow: { name: "set_workflow", group: "config", owner: "gate_captain", summary: "narrate / info_every_ms / heartbeat_every_ms / review_every_close / scan_mode(triggered|every_close) / fast_move_pct / paused=true 直接生效;watchlist / watch_only / timeframe / playbook_text / paused=false / brain / brain_model / cheap_brain / cheap_brain_model 只会生成「设置提议」卡,用户在界面上点确认才生效(返回 proposal_id);风险/杠杆/止损距离/净盈亏比/持仓与开仓上限/日亏停/仓位倍率属于执行层,改它们用 set_execution_policy;自动执行、执行通道只能由用户在界面上改。", doc: "set_workflow{\"patch\":{…}}:narrate / info_every_ms / heartbeat_every_ms / review_every_close / scan_mode(triggered|every_close) / fast_move_pct / paused=true 直接生效;watchlist / watch_only / timeframe / playbook_text / paused=false / brain / brain_model / cheap_brain / cheap_brain_model 只会生成「设置提议」卡,用户在界面上点确认才生效(返回 proposal_id);风险/杠杆/止损距离/净盈亏比/持仓与开仓上限/日亏停/仓位倍率属于执行层,改它们用 set_execution_policy;自动执行、执行通道只能由用户在界面上改。" },
  get_execution_policy: { name: "get_execution_policy", group: "read", owner: "portfolio_manager", summary: "执行层参数(所有机会来源共用):每笔风险、杠杆、止损底线(stop_floor_mode=pct 按 min_stop_pct 百分比 / atr 按 min_stop_atr×stop_floor_atr_tf 周期 ATR)与止损上限、净盈亏比、同时持仓/每日开仓上限、日亏停、仓位倍率模式,以及可调区间、你能直接改的区间、今日用量;stop_conversions 给出观察列表每个币的 ATR 占价格百分比和当前实际最小止损百分比,risk_per_trade_usdt 是打到止损大约亏多少。用户问「为什么候选被挡/参数在哪」时先看它。", doc: "get_execution_policy{}:执行层参数(所有机会来源共用):每笔风险、杠杆、止损底线(stop_floor_mode=pct 按 min_stop_pct 百分比 / atr 按 min_stop_atr×stop_floor_atr_tf 周期 ATR)与止损上限、净盈亏比、同时持仓/每日开仓上限、日亏停、仓位倍率模式,以及可调区间、你能直接改的区间、今日用量;stop_conversions 给出观察列表每个币的 ATR 占价格百分比和当前实际最小止损百分比,risk_per_trade_usdt 是打到止损大约亏多少。用户问「为什么候选被挡/参数在哪」时先看它。" },
  set_execution_policy: { name: "set_execution_policy", group: "config", owner: "portfolio_manager", summary: "改执行层参数。模拟盘且每个值都在 agent_direct 区间内 → 直接生效;超区间或实盘 → 只生成「设置提议」卡,用户在界面确认才生效(返回 proposal_id)。只在用户明确要求时调用;不要为了让某一单能下而调低止损下限——先建议改策略的止损倍数。", doc: "set_execution_policy{\"patch\":{\"min_stop_pct\":1.2,\"min_net_rr\":1.8}} 或 {\"patch\":{\"stop_floor_mode\":\"atr\",\"stop_floor_atr_tf\":\"1h\",\"min_stop_atr\":1}}:改执行层参数(键:risk_pct/leverage/margin_mode/stop_floor_mode(pct/atr)/stop_floor_atr_tf(15m/1h/4h)/min_stop_pct(只在 pct 模式生效)/max_stop_pct/min_stop_atr/min_net_rr/max_open_threads/max_opens_per_day/daily_loss_stop_pct/sizing_agent)。模拟盘且每个值都在 agent_direct 区间内 → 直接生效;超区间或实盘 → 只生成「设置提议」卡,用户在界面确认才生效(返回 proposal_id)。只在用户明确要求时调用;不要为了让某一单能下而调低止损下限——先建议改策略的止损倍数。" },
  run_scan: { name: "run_scan", group: "research", owner: "thread_manager", summary: "立刻扫描一个币或整个观察列表。", doc: "run_scan{\"symbol\":\"可选\"}:立刻扫描一个币或整个观察列表。" },
  run_info: { name: "run_info", group: "research", owner: "radar", summary: "立刻跑一次信息员。", doc: "run_info{}:立刻跑一次信息员。" },
  run_review: { name: "run_review", group: "research", owner: "thread_manager", summary: "立刻复查一条线程。", doc: "run_review{\"id\":\"thr-…\"}:立刻复查一条线程。" },
  remember: { name: "remember", group: "config", owner: "gate_captain", summary: "用户明确要求\"记住\"某个偏好/教训时用;用户自己说的直接生效,你自己总结的不要用它(交给复盘提炼)。", doc: "remember{\"content\":\"一句话\",\"kind\":\"preference|lesson|fact\",\"symbol\":\"BTCUSDT 或 null\",\"tags\":[\"…\"]}:用户明确要求\"记住\"某个偏好/教训时用;用户自己说的直接生效,你自己总结的不要用它(交给复盘提炼)。" },
  recall: { name: "recall", group: "read", owner: "gate_captain", summary: "查长期记忆(已批准的教训/偏好/交易事实)。", doc: "recall{\"query\":\"关键词(≥3 字)\",\"symbol\":\"可选\"}:查长期记忆(已批准的教训/偏好/交易事实)。" },
  forget_memory: { name: "forget_memory", group: "config", owner: "gate_captain", summary: "用户要求忘掉某条记忆时用。", doc: "forget_memory{\"id\":\"mem-…\"}:用户要求忘掉某条记忆时用。" },
  get_team: { name: "get_team", group: "read", owner: "gate_captain", summary: "九个角色的状态、最近任务与待阅交接。", doc: "get_team{}:九个角色的状态、最近任务与待阅交接。" },
  get_portfolio: { name: "get_portfolio", group: "read", owner: "portfolio_manager", summary: "账户级敞口快照(总/净/簇/止损预算/未保护腿)与组合政策。", doc: "get_portfolio{}:账户级敞口快照(总/净/簇/止损预算/未保护腿)与组合政策。" },
  get_risk_alerts: { name: "get_risk_alerts", group: "read", owner: "risk_sentinel", summary: "风控哨兵的开放告警与等级;有 high/critical 时新开仓会被挡,先告诉用户原因。", doc: "get_risk_alerts{}:风控哨兵的开放告警与等级;有 high/critical 时新开仓会被挡,先告诉用户原因。" },
  get_screen: { name: "get_screen", group: "read", owner: "radar", summary: "Radar 最近一次筛选(候选、契合度、提案)。", doc: "get_screen{\"horizon\":\"short|swing|weekly\"}:Radar 最近一次筛选(候选、契合度、提案)。" },
  get_brief: { name: "get_brief", group: "read", owner: "gate_captain", summary: "Gate Captain 最近一份值班简报。", doc: "get_brief{}:Gate Captain 最近一份值班简报。" },
  get_reviewer_cards: { name: "get_reviewer_cards", group: "read", owner: "reviewer", summary: "最近平仓的复盘卡(R、离场原因、保护是否到位)与批次决策。", doc: "get_reviewer_cards{\"limit\":20}:最近平仓的复盘卡(R、离场原因、保护是否到位)与批次决策。" },
  run_screen: { name: "run_screen", group: "research", owner: "radar", summary: "让 Radar 立刻筛一轮,有预算与去重。", doc: "run_screen{\"horizon\":\"short|swing|weekly\"}:让 Radar 立刻筛一轮,有预算与去重。" },
  ack_handoff: { name: "ack_handoff", group: "act", owner: "gate_captain", summary: "用户看过某条交接后标已阅(不是批准)。", doc: "ack_handoff{\"id\":\"hof-…\"}:用户看过某条交接后标已阅(不是批准)。" },
  list_intents: { name: "list_intents", group: "read", owner: "executor", summary: "待用户确认/进行中的下单意图(开仓、平仓)。", doc: "list_intents{\"status\":\"pending_approval\"}:待用户确认/进行中的下单意图(开仓、平仓)。" },
  approve_intent: { name: "approve_intent", group: "act", owner: "gate_captain", summary: "用户明确让你执行时,批准一条 pending_approval 的意图。默认设置下这会真的下到当前执行通道(执行前代码还会重跑全部闸,被拒就把原因告诉用户);如果用户在设置里开了「对话执行需人批」,它不会下单,只会把确认卡推到界面,由用户亲自点。批准前先 list_intents 核对 symbol/方向/数量/止损并在回复里逐字复述;用户没有明确说\"执行/批准/下单\"就不要调。", doc: "approve_intent{\"id\":\"int-…\"}:用户明确让你执行时,批准一条 pending_approval 的意图。默认设置下这会真的下到当前执行通道(执行前代码还会重跑全部闸,被拒就把原因告诉用户);如果用户在设置里开了「对话执行需人批」,它不会下单,只会把确认卡推到界面,由用户亲自点。批准前先 list_intents 核对 symbol/方向/数量/止损并在回复里逐字复述;用户没有明确说\"执行/批准/下单\"就不要调。" },
  reject_intent: { name: "reject_intent", group: "act", owner: "gate_captain", summary: "否决一条待批意图。", doc: "reject_intent{\"id\":\"int-…\"}:否决一条待批意图。" },
  request_execution: { name: "request_execution", group: "act", owner: "executor", summary: "不下单,只把确认卡推到界面(用户想自己点的时候用)。", doc: "request_execution{\"id\":\"int-…\"}:不下单,只把确认卡推到界面(用户想自己点的时候用)。" },
  get_judgment_ledger: { name: "get_judgment_ledger", group: "read", owner: "reviewer", summary: "判断账本 jl-v2 摘要,按层给样本量、判断增量(模型 vs 议会/机械)、regret_hold(该走没走)与 regret_exit(不该走走了)的均值/中位数/截尾均值。用户问「模型判断值不值/拿着还是走掉更亏」用这个。", doc: "get_judgment_ledger{\"dim\":\"strategy|trigger_kind|prompt_version|holding_reason|all\",\"since_days\":30,\"source\":\"online|replay|trader|backfill|all\",\"strategy_id\":\"可选\"}:判断账本 jl-v2 摘要,按层给样本量、判断增量(模型 vs 议会/机械)、regret_hold(该走没走)与 regret_exit(不该走走了)的均值/中位数/截尾均值。用户问「模型判断值不值/拿着还是走掉更亏」用这个。" },
  list_candidates: { name: "list_candidates", group: "read", owner: "reviewer", summary: "影子候选(不下单的策略候选)最近列表 + 汇总(计划腿/吊灯腿期望、候选 × 模型配对)。", doc: "list_candidates{\"limit\":20,\"symbol\":\"可选\",\"strategy_id\":\"可选\"}:影子候选(不下单的策略候选)最近列表 + 汇总(计划腿/吊灯腿期望、候选 × 模型配对)。" },
  list_my_strategies: { name: "list_my_strategies", group: "read", owner: "strategy_lab", summary: "研究侧「我的策略」对象列表与最新回测摘要。", doc: "list_my_strategies{\"q\":\"可选搜索\",\"filter\":\"all|live|watchlist|alerts|archived\",\"limit\":20}:研究侧「我的策略」对象列表与最新回测摘要。" },
  get_backtest_report: { name: "get_backtest_report", group: "read", owner: "strategy_lab", summary: "一份回测报告的摘要(总收益、最大回撤、笔数、胜率、平均持有、逐笔收益的均值/中位数/截尾均值、分段)。", doc: "get_backtest_report{\"id\":\"报告 id\"} 或 {\"strategy_id\":\"研究策略 id\"}:一份回测报告的摘要(总收益、最大回撤、笔数、胜率、平均持有、逐笔收益的均值/中位数/截尾均值、分段)。" },
  get_evolution: { name: "get_evolution", group: "read", owner: "strategy_lab", summary: "进化页方格摘要(各角色最近每天红黄绿与今天的判断用量)。", doc: "get_evolution{\"role\":\"可选角色,如 thread_manager\",\"days\":30}:进化页方格摘要(各角色最近每天红黄绿与今天的判断用量)。" },
  get_universe_scan: { name: "get_universe_scan", group: "read", owner: "radar", summary: "OKX 全市场每日扫描的最新结果(扫了多少、候选前几名)。", doc: "get_universe_scan{\"limit\":20}:OKX 全市场每日扫描的最新结果(扫了多少、候选前几名)。" },
  recommend_assets: { name: "recommend_assets", group: "research", owner: "strategy_lab", summary: "资产 × 短线(3m/5m/15m)/中线(1h/4h)/长线(12h/1d)推荐:每格适不适合、方向、建议策略族、证据(成交额/日线状态/扫描名次,全是代码算的)。不给 symbols 就取全市场扫描前 top_n(缺省 8)。用户问「交易什么/推荐几个币/X 适合短线还是长线/适合什么策略」时先调它;界面会渲染推荐卡,卡上有「去研究台验证」按钮会自动开矩阵研究。回答只挑重点,说清哪些格子不适合及原因(例如小市值不做短线);推荐只是「值得研究」,不是「能赚钱」,赚不赚要等研究结果。", doc: "recommend_assets{\"symbols\":[\"SOL\",\"DOGE\"],\"horizons\":[\"short\",\"mid\",\"long\"],\"market\":\"perp\"}:资产 × 短线(3m/5m/15m)/中线(1h/4h)/长线(12h/1d)推荐:每格适不适合、方向、建议策略族、证据(成交额/日线状态/扫描名次,全是代码算的)。不给 symbols 就取全市场扫描前 top_n(缺省 8)。用户问「交易什么/推荐几个币/X 适合短线还是长线/适合什么策略」时先调它;界面会渲染推荐卡,卡上有「去研究台验证」按钮会自动开矩阵研究。回答只挑重点,说清哪些格子不适合及原因(例如小市值不做短线);推荐只是「值得研究」,不是「能赚钱」,赚不赚要等研究结果。" },
  run_review_batch: { name: "run_review_batch", group: "research", owner: "reviewer", summary: "让 Reviewer 批量复盘;受暂停、预算与去重约束。", doc: "run_review_batch{}:让 Reviewer 批量复盘;受暂停、预算与去重约束。" },
  run_experiment: { name: "run_experiment", group: "research", owner: "strategy_lab", summary: "让 Strategy Lab 跑一次可复现实验。", doc: "run_experiment{}:让 Strategy Lab 跑一次可复现实验。" },
  start_matrix_study: { name: "start_matrix_study", group: "research", owner: "strategy_lab", summary: "异步开矩阵研究;只传需要覆盖的参数;完成后回报本会话。", doc: "start_matrix_study{\"recommendation_id\":\"可选\",\"symbols\":[\"BTC\"],\"timeframes\":[\"4h\"],\"families\":[\"breakout\"],\"arms\":[\"code\",\"code_judge\"],\"market\":\"spot|perp\"}:异步开矩阵研究;只传需要覆盖的参数;完成后回报本会话。" },
  get_matrix_study: { name: "get_matrix_study", group: "read", owner: "strategy_lab", summary: "读矩阵研究进度、结论与最终候选。", doc: "get_matrix_study{\"id\":\"可选\"}:读矩阵研究进度、结论与最终候选。" },
  adopt_matrix_finalist: { name: "adopt_matrix_finalist", group: "research", owner: "strategy_lab", summary: "用户同意后把通过预检的最终候选存成研究策略。", doc: "adopt_matrix_finalist{\"study_id\":\"…\",\"finalist_id\":\"…\"}:用户同意后把通过预检的最终候选存成研究策略。" },
  get_agent_strategy: { name: "get_agent_strategy", group: "read", owner: "strategy_lab", summary: "读 agent 当前策略与模式。", doc: "get_agent_strategy{}:读 agent 当前策略与模式。" },
  set_agent_strategy: { name: "set_agent_strategy", group: "config", owner: "strategy_lab", summary: "仅在用户明确同意后切换当前策略;实盘确认由用户在界面完成。", doc: "set_agent_strategy{\"kind\":\"free|strategy\",\"strategy_id\":\"可选\",\"version\":1,\"mode\":\"agent|jev|auto|signal_only\"}:仅在用户明确同意后切换当前策略;实盘确认由用户在界面完成。「每笔确认」模式已下线。" },
  get_asp_overview: { name: "get_asp_overview", group: "read", owner: "asp_agent", summary: "只读 ASP 身份、上架、服务、订阅分组、发布、接单轮询、可领收入和错误;未就绪的块返回 ready:false。", doc: "get_asp_overview{}:只读 ASP 身份、上架、服务、订阅分组、发布、接单轮询、可领收入和错误;未就绪的块返回 ready:false。" },
  list_asp_services: { name: "list_asp_services", group: "read", owner: "asp_agent", summary: "只读七项对外服务的 serviceId、英文名称、说明、计费、注册和交付统计。", doc: "list_asp_services{}:只读七项对外服务的 serviceId、英文名称、说明、计费、注册和交付统计。" },
  list_asp_tasks: { name: "list_asp_tasks", group: "read", owner: "asp_agent", summary: "只读 provider 按次/订阅接单与交付账本,含远端回查状态。", doc: "list_asp_tasks{\"status\":\"open|all\",\"limit\":20}:只读 provider 按次/订阅接单与交付账本,含远端回查状态。" },
  list_asp_subscribers: { name: "list_asp_subscribers", group: "read", owner: "asp_agent", summary: "只读卖方订阅者分组列表;买方标识脱敏。", doc: "list_asp_subscribers{\"limit\":20}:只读卖方订阅者分组列表;买方标识脱敏。" },
  list_market_inbox: { name: "list_market_inbox", group: "read", owner: "asp_agent", summary: "只读买方最近入站信号与解析状态。", doc: "list_market_inbox{\"limit\":20}:只读买方最近入站信号与解析状态。" },
};

export const AGENT_REGISTRY: Record<BotRole, AgentSpec> = {
  gate_captain: { name: "Gate Captain", callsign: "HELM", tagline: "汇总团队状态、目标与待办",
    tools: ["get_state", "list_threads", "get_thread", "get_episode", "list_history", "propose_thread", "close_thread", "set_workflow", "get_execution_policy", "set_execution_policy", "run_scan", "run_info", "run_review", "remember", "recall", "forget_memory", "get_team", "get_portfolio", "get_risk_alerts", "get_screen", "get_brief", "get_reviewer_cards", "run_screen", "ack_handoff", "list_intents", "approve_intent", "reject_intent", "request_execution", "get_judgment_ledger", "list_candidates", "list_my_strategies", "get_backtest_report", "get_evolution", "get_universe_scan", "recommend_assets", "run_review_batch", "run_experiment", "start_matrix_study", "get_matrix_study", "adopt_matrix_finalist", "get_agent_strategy", "set_agent_strategy", "get_asp_overview"], skills: ["strategy_loop"],
    loop: { cadence: "每 30 分钟检查每日简报", affected_by_pause: false, graph: {"entry": "trigger", "nodes": [{"id": "trigger", "label": "简报定时检查", "kind": "trigger"}, {"id": "read", "label": "团队、风险与待阅交接", "kind": "read"}, {"id": "work", "label": "代码汇总每日简报", "kind": "code"}, {"id": "output", "label": "简报与活动流", "kind": "output"}], "edges": [{"from": "trigger", "to": "read"}, {"from": "read", "to": "work"}, {"from": "work", "to": "output"}]} } },
  radar: { name: "Radar", callsign: "RADAR", tagline: "筛选候选与市场信息",
    tools: ["get_state", "recall", "get_team", "get_screen", "run_screen", "run_info", "get_universe_scan"], skills: [],
    loop: { cadence: "按筛选周期与信息员频率", affected_by_pause: true, graph: {"entry": "trigger", "nodes": [{"id": "trigger", "label": "三档筛选到期 / 手动", "kind": "trigger"}, {"id": "read", "label": "行情与策略条件", "kind": "read"}, {"id": "work", "label": "硬门过滤与确定性排名", "kind": "code"}, {"id": "model", "label": "预算允许时选短名单", "kind": "model"}, {"id": "output", "label": "候选与观察列表提案", "kind": "output"}, {"id": "handoff", "label": "交总协调查阅", "kind": "handoff", "to_role": "gate_captain"}], "edges": [{"from": "trigger", "to": "read"}, {"from": "read", "to": "work"}, {"from": "work", "to": "model"}, {"from": "model", "to": "output"}, {"from": "output", "to": "handoff"}]} } },
  thread_manager: { name: "Thread Manager", callsign: "THREAD", tagline: "维持交易论点与线程连续性",
    tools: ["get_state", "recall", "get_team", "list_threads", "get_thread", "get_episode", "list_history", "run_scan", "run_review", "propose_thread", "close_thread", "get_agent_strategy", "get_execution_policy"], skills: [],
    loop: { cadence: "事件、K 线收盘与心跳", affected_by_pause: true, graph: {"entry": "trigger", "nodes": [{"id": "trigger", "label": "触发器 / 线程事件", "kind": "trigger"}, {"id": "read", "label": "证据、线程与记忆", "kind": "read"}, {"id": "work", "label": "判断并更新交易论点", "kind": "model"}, {"id": "gate", "label": "代码预算与风险闸", "kind": "gate"}, {"id": "output", "label": "判断记录与待批意图", "kind": "output"}, {"id": "handoff", "label": "授权后交执行服务", "kind": "handoff", "to_role": "executor"}], "edges": [{"from": "trigger", "to": "read"}, {"from": "read", "to": "work"}, {"from": "work", "to": "gate"}, {"from": "gate", "to": "output"}, {"from": "output", "to": "handoff"}]} } },
  strategy_lab: { name: "Strategy Lab", callsign: "LAB", tagline: "研究、实验与策略候选",
    tools: ["get_state", "recall", "get_team", "run_experiment", "list_my_strategies", "get_backtest_report", "list_candidates", "get_evolution", "get_judgment_ledger", "get_universe_scan", "recommend_assets", "start_matrix_study", "get_matrix_study", "adopt_matrix_finalist", "get_agent_strategy", "set_agent_strategy"], skills: ["strategy_loop"],
    loop: { cadence: "每 30 分钟检查实验条件", affected_by_pause: false, graph: {"entry": "trigger", "nodes": [{"id": "trigger", "label": "到期 / 新平仓 / 手动", "kind": "trigger"}, {"id": "read", "label": "策略版本与历史数据", "kind": "read"}, {"id": "work", "label": "冻结实验并计算结果", "kind": "code"}, {"id": "output", "label": "实验结果与候选提案", "kind": "output"}, {"id": "handoff", "label": "交总协调查阅", "kind": "handoff", "to_role": "gate_captain"}], "edges": [{"from": "trigger", "to": "read"}, {"from": "read", "to": "work"}, {"from": "work", "to": "output"}, {"from": "output", "to": "handoff"}]} } },
  portfolio_manager: { name: "Portfolio Manager", callsign: "BOOK", tagline: "核算敞口、簇集中度与风险预算",
    tools: ["get_state", "recall", "get_team", "get_portfolio", "list_threads", "get_thread", "list_intents", "get_execution_policy", "set_execution_policy"], skills: [],
    loop: { cadence: "账户轮询与提案触发", affected_by_pause: false, graph: {"entry": "trigger", "nodes": [{"id": "trigger", "label": "账户轮询 / 提案", "kind": "trigger"}, {"id": "read", "label": "账户与线程快照", "kind": "read"}, {"id": "work", "label": "敞口、簇与止损预算", "kind": "code"}, {"id": "gate", "label": "组合硬闸与有界仓位意见", "kind": "gate"}, {"id": "output", "label": "组合快照与提案意见", "kind": "output"}], "edges": [{"from": "trigger", "to": "read"}, {"from": "read", "to": "work"}, {"from": "work", "to": "gate"}, {"from": "gate", "to": "output"}]} } },
  risk_sentinel: { name: "Risk Sentinel", callsign: "SENTINEL", tagline: "检查不变量、告警与拒绝原因",
    tools: ["get_state", "recall", "get_team", "get_risk_alerts", "get_portfolio", "get_thread", "get_episode", "list_intents", "get_execution_policy", "set_execution_policy"], skills: [],
    loop: { cadence: "账户轮询触发", affected_by_pause: false, graph: {"entry": "trigger", "nodes": [{"id": "trigger", "label": "账户轮询", "kind": "trigger"}, {"id": "read", "label": "账户、保护与通道健康", "kind": "read"}, {"id": "work", "label": "代码检查风险不变量", "kind": "code"}, {"id": "gate", "label": "拒绝新增风险或收紧", "kind": "gate"}, {"id": "output", "label": "指纹告警与恢复条件", "kind": "output"}], "edges": [{"from": "trigger", "to": "read"}, {"from": "read", "to": "work"}, {"from": "work", "to": "gate"}, {"from": "gate", "to": "output"}]} } },
  reviewer: { name: "Reviewer", callsign: "AUDIT", tagline: "平仓复盘与待批教训",
    tools: ["get_state", "recall", "get_team", "list_history", "get_reviewer_cards", "run_review_batch", "get_judgment_ledger", "list_candidates", "get_episode", "get_thread", "get_backtest_report", "get_evolution"], skills: [],
    loop: { cadence: "平仓事件与每 30 分钟检查", affected_by_pause: true, graph: {"entry": "trigger", "nodes": [{"id": "trigger", "label": "平仓 / 批次定时检查", "kind": "trigger"}, {"id": "read", "label": "平仓卡与已有教训", "kind": "read"}, {"id": "work", "label": "代码复盘 / 有预算时提炼", "kind": "model"}, {"id": "output", "label": "复盘卡与待批教训", "kind": "output"}, {"id": "handoff", "label": "交总协调查阅", "kind": "handoff", "to_role": "gate_captain"}, {"id": "human", "label": "操盘手批准教训", "kind": "human"}], "edges": [{"from": "trigger", "to": "read"}, {"from": "read", "to": "work"}, {"from": "work", "to": "output"}, {"from": "output", "to": "handoff"}, {"from": "handoff", "to": "human"}]} } },
  executor: { name: "Executor", callsign: "EXEC", tagline: "解释授权执行、保护与对账",
    tools: ["get_state", "recall", "get_team", "list_intents", "get_thread", "request_execution", "get_execution_policy"], skills: [],
    loop: { cadence: "授权请求与账户轮询", affected_by_pause: true, graph: {"entry": "trigger", "nodes": [{"id": "trigger", "label": "授权请求 / 对账轮询", "kind": "trigger"}, {"id": "gate", "label": "执行控制与重闸", "kind": "gate"}, {"id": "work", "label": "提交并维护保护腿", "kind": "code"}, {"id": "read", "label": "回执与订单核对", "kind": "read"}, {"id": "output", "label": "意图、线程与结算记录", "kind": "output"}], "edges": [{"from": "trigger", "to": "gate"}, {"from": "gate", "to": "work"}, {"from": "work", "to": "read"}, {"from": "read", "to": "output"}]} } },
  asp_agent: { name: "ASP Agent", callsign: "MARKET", tagline: "管理信号市场的入站、交付与售后",
    tools: ["get_state", "recall", "get_team", "get_asp_overview", "list_asp_services", "list_asp_tasks", "list_asp_subscribers", "list_market_inbox"], skills: [],
    loop: { cadence: "接单每分钟、入站按设置轮询", affected_by_pause: false, graph: {"entry": "trigger", "nodes": [{"id": "trigger", "label": "provider-tasks 轮询 / 入站事件", "kind": "trigger"}, {"id": "read", "label": "serviceId、任务与订阅集合", "kind": "read"}, {"id": "gate", "label": "处理器、暂停与参数校验", "kind": "gate"}, {"id": "work", "label": "接单交付 / 按服务扇出", "kind": "code"}, {"id": "output", "label": "入站、投递与回查账本", "kind": "output"}, {"id": "handoff", "label": "异常与售后交总协调", "kind": "handoff", "to_role": "gate_captain"}, {"id": "human", "label": "市场页激活、领款与售后", "kind": "human"}], "edges": [{"from": "trigger", "to": "read"}, {"from": "read", "to": "gate"}, {"from": "gate", "to": "work"}, {"from": "work", "to": "output"}, {"from": "output", "to": "handoff"}, {"from": "handoff", "to": "human"}]} } },
};

export function isBotRole(role: unknown): role is BotRole { return typeof role === 'string' && (BOT_ROLES as string[]).includes(role); }
export function chatRole(role: string | null | undefined): BotRole { return isBotRole(role) ? role : 'gate_captain'; }
export function agentSessionId(role: BotRole): string { return role === 'gate_captain' ? 'default' : `agent:${role}`; }
export function isCanonicalSession(id: string): boolean { return BOT_ROLES.some((role) => agentSessionId(role) === id); }
export function agentTools(role: BotRole): AgentTool[] {
  return AGENT_REGISTRY[role].tools.map((name) => { const t = CHAT_TOOL_CATALOG[name]!; return { name, group: t.group, summary: t.summary }; });
}
export function toolAccessError(role: BotRole, name: string): string | null {
  if (AGENT_REGISTRY[role].tools.includes(name)) return null;
  const t = Object.hasOwn(CHAT_TOOL_CATALOG, name) ? CHAT_TOOL_CATALOG[name] : null;
  return t ? `not_my_tool: ${name} 属于 @${AGENT_REGISTRY[t.owner].callsign},可以去找它` : `未知工具 ${name}`;
}
