import type { ResearchArmResult,ResearchDataset,ResearchDiagnostics,ResearchUniverse } from '@trade-gate/contracts';
import { factorDecompose } from './factor.js';
import { periodsPerYear } from './calendar.js';
import { decimal,q } from './primitives.js';
const avg=(x:(number|null|undefined)[])=>{const values=x.filter((n):n is number=>typeof n==='number'&&Number.isFinite(n));return values.length?values.reduce((a,b)=>a+b,0)/values.length:null;};
export function diagnostics(arm:ResearchArmResult,datasets:ResearchDataset[],u?:ResearchUniverse,slippage?:bigint,gateStats?:ResearchDiagnostics['gate_stats']):ResearchDiagnostics {
 const trades=arm.trades,byReason=new Map<string,typeof trades>();for(const t of trades){const rows=byReason.get(t.reason)??[];rows.push(t);byReason.set(t.reason,rows);}
 const bins=[-3,-2,-1,0,1,2,3,5],counts=Array<number>(bins.length-1).fill(0);
 for(const t of trades){if(t.net_r===null)continue;let i=bins.findIndex((edge,j)=>j>0&&t.net_r!<edge)-1;if(i<0)i=t.net_r<bins[0]!?0:counts.length-1;counts[i]=counts[i]!+1;}
 const holds=trades.flatMap(t=>t.holding_bars===undefined?[]:[t.holding_bars]).sort((a,b)=>a-b),middle=Math.floor(holds.length/2);
 const symbols=u?.market_factor.symbols??[datasets[0]!.symbol],weights=u?.market_factor.weights??{[symbols[0]!]: '1'},maps=new Map(datasets.map(d=>[d.symbol,new Map(d.bars.map(b=>[b.close_time,b]))])),step=datasets[0]!.timeframe_ms,returns:number[]=[],market:number[]=[];
 for(let i=1;i<arm.equity.length;i++){const e=arm.equity[i]!,prior=arm.equity[i-1]!;if(i>1&&e.at-prior.at!==step)continue;let factor=0,valid=true;for(const symbol of symbols){const now=maps.get(symbol)?.get(e.at),prev=maps.get(symbol)?.get(e.at-step);if(!now||!prev){valid=false;break;}factor+=Number(weights[symbol])*Math.log(Number(now.close)/Number(prev.close));}if(valid&&Number(e.equity)>0&&Number(prior.equity)>0){returns.push(Math.log(Number(e.equity)/Number(prior.equity)));market.push(factor);}}
 const f=factorDecompose(returns,market,{window_bars:720,periods_per_year:periodsPerYear(step,datasets[0]!.calendar),risk_free_per_bar:Number(datasets[0]!.risk_free_per_bar??0)}),gross=q(arm.metrics.net_pnl)+q(arm.metrics.fees),fees=q(arm.metrics.fees),slip=slippage??trades.reduce((a,t)=>a+q(t.slippage_est??'0'),0n);
 return {...(gateStats?{gate_stats:gateStats}:{}),exit_reasons:[...byReason].sort(([a],[b])=>a.localeCompare(b)).map(([reason,rows])=>({reason,count:rows.length,avg_net_r:avg(rows.map(t=>t.net_r)),net_pnl:decimal(rows.reduce((a,t)=>a+q(t.net_pnl),0n))})),r_histogram:{bins,counts},mae_mfe:{avg_mae_r:avg(trades.map(t=>t.mae_r)),avg_mfe_r:avg(trades.map(t=>t.mfe_r)),winners_avg_mfe_r:avg(trades.filter(t=>q(t.net_pnl)>0n).map(t=>t.mfe_r)),losers_avg_mfe_r:avg(trades.filter(t=>q(t.net_pnl)<0n).map(t=>t.mfe_r))},cost_share:{fees:arm.metrics.fees,slippage_est:decimal(slip),gross_pnl:decimal(gross),cost_over_gross_abs:gross!==0n?Number(fees+slip)/Math.abs(Number(gross)):null},factor:f.status==='ok'?{status:'ok',beta:f.beta!,alpha_annualized:f.alpha_annualized!,alpha_share:f.alpha_share!,beta_share:f.beta_share!,residual_max_dd:f.residual!.max_drawdown,residual_sharpe:f.residual!.sharpe,r2:f.r2!}:{status:'insufficient'},holding_bars:{avg:avg(holds),median:holds.length?(holds.length%2?holds[middle]!:(holds[middle-1]!+holds[middle]!)/2):null,max:holds.at(-1)??null},note:'按退出批次统计；intrabar 出场根仅采用已确认触发价，不假定另一极值先于出场，MAE/MFE 为保守已观测偏移。R 分箱首尾吸收越界样本。gross_pnl 含末尾盯市、未扣费但已含执行滑点；费用/滑点比率用于诊断，不能再次从权益扣除。单资产以自身买入持有作为市场代理；factor 需至少 1440 收益样本。'};
}
