import { describe,it,expect } from 'vitest';
import type { Brain } from '../../../src/demo/brain.js';
import { makeDecider,resample,contextFor } from '../../../src/demo/research/agent.js';
import type { DecisionView } from '../../../src/demo/research/engine.js';
import { fixture,params } from './fixtures.js';
const d=fixture(),r=params(),last=d.bars[60]!;
const v:DecisionView={at:last.close_time,arm:'b_agent:0',symbol:'TEST-USDT',timeframe_ms:d.timeframe_ms,bars:d.bars.slice(0,61),policy:r.policy,candidate:null,account:{cash:'10000',equity:'10000'},position:null,previous_summary:null,opens_today:0};
const reply=(text:string)=>({text,model:'fixture',input_tokens:1,output_tokens:1,latency_ms:1});
const judgment={action:'PROPOSE',direction:'long',confidence:.8,headline:'fixture',thesis:'结构测试',reasons:['行情提供价格 [E1]'],evidence_refs:['E1'],invalidation:null,invalidation_price:null,target_price:null,watch_conditions:[],proposal:{market:'spot',direction:'long',entry:'market',limit_price:null,entry_zone:null,stop_price:(Number(last.close)*.98).toFixed(8),take_profit_price:(Number(last.close)*1.04).toFixed(8),take_profits:[],rationale:'结构测试'}};
describe('研究策略契约适配',()=>{
 it('frozen B prompt contains only strategy rules and primitive evidence',()=>{const built=contextFor(v,null,'playbook watch_eligible E6 E7 议会').built;const prompt=built.system_text+built.user_text;for(const forbidden of ['playbook','watch_eligible','E6','E7','议会'])expect(prompt).not.toContain(forbidden);expect(prompt).toContain('donchian_breakout');expect(prompt).toContain(last.close);});
 it('source strategy contributes original rules but not live scans or future performance',()=>{const strategy={id:'source',version:1,name:'原策略',horizon:'swing',rules:{entry:['突破后进入'],exit:['结构失效离开'],invalidation:['跌破确认支撑']},params:{},checklist:{required:['E6'],watch_eligible:true},eval_stats:{future_profit:'999999'}} as unknown as import('../../../src/demo/strategies.js').StrategySpec;const prompt=contextFor(v,strategy,'playbook').built.user_text;expect(prompt).toContain('突破后进入');for(const term of ['E6','watch_eligible','future_profit'])expect(prompt).not.toContain(term);});
 it('B routes a valid existing Judgment through live parser and gates',async()=>{const brain:Brain={name:'fixture',complete:async()=>reply(JSON.stringify(judgment))};const action=await makeDecider(brain,r.execution,null,'')(v);expect(action.action,JSON.stringify(action)).toBe('enter');expect(action.entry?.stop).toBe(judgment.proposal.stop_price);});
 it('B fails closed for unsupported limit execution rather than silently converting it',async()=>{const j={...judgment,proposal:{...judgment.proposal,entry:'limit',limit_price:last.close}};const brain:Brain={name:'fixture',complete:async()=>reply(JSON.stringify(j))};const action=await makeDecider(brain,r.execution,null,'')(v);expect(action.action).toBe('blocked');expect(action.gate_errors.join()).toContain('requires_spot_long_market');});
 it('C rejects injected economic fields and repairs using an actual restricted schema',async()=>{let calls=0;const brain:Brain={name:'fixture',complete:async()=>reply(JSON.stringify(++calls===1?{action:'follow',reason:'x',evidence_refs:['E1'],stop:'0'}:{action:'skip',reason:'fixture skip',evidence_refs:['E1']}))};const action=await makeDecider(brain,r.execution,null,'')({...v,arm:'c_filter:0'});expect(calls).toBe(2);expect(action.action).toBe('skip');expect(action.entry).toBeUndefined();});
 it('resampling excludes incomplete or unavailable UTC buckets and does not invent lower timeframes',()=>{const bars=d.bars.slice(0,7);expect(resample(bars,3600000,14400000,bars.at(-1)!.close_time)).toHaveLength(1);expect(resample(bars,3600000,900000,bars.at(-1)!.close_time)).toEqual([]);});
});
