import { describe,it,expect } from 'vitest';
import { SpotLedger } from '../../../src/demo/research/ledger.js';
import { runReplay, type Decider } from '../../../src/demo/research/engine.js';
import { hash,q,decimal,dataset,request } from '../../../src/demo/research/primitives.js';
import { candidateLabels,selectionEvaluation } from '../../../src/demo/research/evaluation.js';
import { fixture,params } from './fixtures.js';
const ruleAgent:Decider=async v=>v.arm.startsWith('c_filter')?{action:'follow',reason:'fixture follow all',gate_errors:[],evidence_refs:[]}:v.position?{action:'hold',reason:'fixture fixed protection',gate_errors:[],evidence_refs:[]}:v.candidate?{action:'enter',reason:'fixture deterministic reference',gate_errors:[],evidence_refs:[],entry:v.candidate}:{action:'no_trade',reason:'fixture no setup',gate_errors:[],evidence_refs:[]};
describe('研究共用引擎',()=>{
 it('A / B rule oracle / C follow all have exactly equal cash equity and fills',async()=>{const r=await runReplay(fixture(),params(),ruleAgent);expect(r.status).toBe('completed');expect(r.arms).toHaveLength(5);const a=r.arms[0]!;expect(a.trades.length).toBeGreaterThan(0);for(const b of r.arms.slice(1)){expect(b.equity).toEqual(a.equity);expect(b.trades).toEqual(a.trades);}});
 it('stores bounded historical inputs, independent repeat memory; recorded replay uses zero model calls',async()=>{const seen:string[]=[];const decider:Decider=async v=>{expect(v.bars.every(b=>b.close_time<=v.at&&b.available_at<=v.at)).toBe(true);if(v.previous_summary===null)seen.push(v.arm);return ruleAgent(v);};const r=await runReplay(fixture(),params(),decider);expect(seen).toContain('b_agent:1');expect(seen).toContain('c_filter:1');const replay=await runReplay(fixture(),params(),async()=>{throw new Error('must not call')},{replay:r.recordings});expect(replay.status).toBe('completed');expect(hash(replay.arms)).toBe(hash(r.arms));});
 it('a corrupt recorded input fails closed instead of resampling model',async()=>{const r=await runReplay(fixture(),params(),ruleAgent);r.recordings[0]!.input.account.cash='999';const replay=await runReplay(fixture(),params(),ruleAgent,{replay:r.recordings});expect(replay.status).toBe('failed');expect(replay.comparison).toEqual([]);});
 it('protective gap wins over queued agent exit; fees conserve cash and lower equity',()=>{const cfg={...params().execution,fee_rate:'0.01',slippage_bps:'0',max_allocation:'1',risk_fraction:'0.1'};const l=new SpotLedger(cfg);l.pending={action:'enter',entry:{candidate_id:'c',stop:'90',target:'120',reason:'x'}};const b={...fixture().bars[0]!,open:'100',high:'101',low:'99',close:'100'};l.step(b);expect(l.cash).toBeLessThan(q('10000'));expect(q(l.equity.at(-1)!.equity)).toBe(q('10000')-l.fees);l.pending={action:'exit',reason:'agent_exit'};l.step({...b,open_time:b.open_time+3600000,close_time:b.close_time+3600000,open:'80',high:'81',low:'79',close:'80'});expect(l.trades[0]!.reason).toBe('stop');expect(l.trades[0]!.exit_price).toBe('80.00000000');expect(l.cash).toBe(q('10000')+q(l.trades[0]!.net_pnl));});
 it('rejects duplicate/missing/invalid OHLC and ambiguous availability',()=>{const d=fixture();expect(dataset(d)).toEqual(d);for(const mutate of [(x:typeof d)=>x.bars.splice(20,1),(x:typeof d)=>x.bars[0]!.available_at++,(x:typeof d)=>x.bars[0]!.high='0']){const x=structuredClone(d);mutate(x);expect(()=>dataset(x)).toThrow();}expect(()=>request({...params(),from_ms:d.bars[1]!.close_time},d)).toThrow('warmup');});
 it('fixed point round trips signed amounts',()=>{for(const s of ['0','0.00000001','12345678.12345678','-123.25'])expect(q(decimal(q(s)))).toBe(q(s));});
 it('labels are post-run and use fixed full-horizon eligibility, with exploratory matched participation control',async()=>{const d=fixture(),p=params(),r=await runReplay(d,p,ruleAgent),labels=candidateLabels(d,p),e=selectionEvaluation(d,p,r);expect(labels.length).toBeGreaterThan(10);expect(e.filter_controls[0]!.skipped).toBe(0);expect(e.filter_controls[0]!.matched_participation.status).toBe('insufficient');expect(r.recordings.every(x=>!JSON.stringify(x.input).includes('net_r'))).toBe(true);});
});
