import {it,expect} from 'vitest';
import {openStateDb} from '../../../src/state-db.js';
import {ResearchStore} from '../../../src/demo/research/store.js';
import {precheck} from '../../../src/demo/research/precheck.js';
import {policyToIR,defaultIR,checkIR} from '../../../src/demo/research/strategy.js';
import {fixture,params} from './fixtures.js';
it('precheck runs no model and exposes unit notional risk/cost conflict with overrideable thresholds',async()=>{const db=openStateDb(':memory:');try{const store=new ResearchStore(db.db),id=store.putDataset(fixture()).id,r=params(id);const body={ir:policyToIR(r.policy!),dataset_id:id,from_ms:r.from_ms,to_ms:r.to_ms,execution:r.execution,thresholds:{min_trades:1,min_gate_pass_rate:0,min_holding_bars:0,min_regime_coverage:0}};const result=await precheck(body,store);expect(result.items.map(i=>i.name)).toEqual(['signal_frequency','min_trades','stop_over_cost','order_gate_pass_rate','stop_fit_rate','holding_vs_timeframe','warmup_coverage','regime_coverage']);expect(result.items.find(i=>i.name==='signal_frequency')!.value).toBeGreaterThan(0);expect(result.items.find(i=>i.name==='order_gate_pass_rate')!.note).not.toContain('risk_cap');expect(result.items.find(i=>i.name==='order_gate_pass_rate')?.threshold).toBe(0);}finally{db.close();}});
// 2026-09-23 结构口径:图上没有止盈时交给追踪止损,「止损 + 追踪出场」也是完整出场周期;止盈、追踪、信号离场全无才不行
it('compile requires a target source, a trailing stop or a signal exit before research can start',()=>{const ir=defaultIR();ir.exit=[];expect(checkIR(ir,'1h').checks.find(c=>c.name==='order_gate_ready')?.ok).toBe(false);const trail=defaultIR();trail.exit=trail.exit.filter(n=>n.primitive!=='structure_target');expect(checkIR(trail,'1h').checks.find(c=>c.name==='order_gate_ready')?.ok).toBe(true);expect(checkIR(defaultIR(),'1h').ok).toBe(true);});
it('precheck follows IR equal_notional even when execution selects risk_fraction',async()=>{const db=openStateDb(':memory:');try{const store=new ResearchStore(db.db),id=store.putDataset(fixture()).id,r=params(id),ir=policyToIR(r.policy!);delete ir.compatibility;ir.risk.sizing={primitive:'equal_notional',params:{max_allocation:'1'}};ir.exit.push({primitive:'chandelier_trail',params:{atr_period:5,multiple:2}});const result=await precheck({ir,dataset_id:id,from_ms:r.from_ms,to_ms:r.to_ms,execution:{...r.execution,sizing_mode:'risk_fraction'}},store);const item=result.items.find(x=>x.name==='order_gate_pass_rate')!;expect(item.value).toBeLessThan(1);expect(item.note).toContain('risk_cap');}finally{db.close();}});
