import {it,expect} from 'vitest';
import {structure,completeBuckets,htfStructure} from '../../../src/demo/research/primitives/structure.js';
import {fixture,STEP,T0} from './fixtures.js';
const bars=[100,104,108,104,100,103,110,106,102,98,94,99].map((c,i)=>({open_time:T0+i*STEP,close_time:T0+(i+1)*STEP-1,available_at:T0+(i+1)*STEP-1,open:String(c+(i>0&&c<[100,104,108,104,100,103,110,106,102,98,94][i-1]!?0.5:-0.5)),close:String(c),high:String(c+1),low:String(c-1),volume:'100'}));
it('pivot is absent until the entire right confirmation window closes',()=>{expect(structure(bars.slice(0,4),2).pivots.find(p=>p.index===2)).toBeUndefined();const p=structure(bars.slice(0,5),2).pivots.find(p=>p.index===2)!;expect(p.kind).toBe('high');expect(p.confirmed_index).toBe(4);expect(p.confirmed_at).toBe(bars[4]!.close_time);});
it('BOS creates the last opposite candle block only at the break and records mitigation causally',()=>{const before=structure(bars.slice(0,6),2),after=structure(bars.slice(0,7),2);expect(before.breaks).toHaveLength(0);expect(after.breaks[0]).toMatchObject({kind:'bos',direction:'up',index:6});expect(after.blocks[0]).toMatchObject({index:4,formed_at:bars[6]!.close_time,lower:'99',upper:'101',mitigated:false});expect(structure(bars,2).blocks[0]!.mitigated_at).toBe(bars[9]!.close_time);});
it('body versus wick bounds are explicit, and high/low confirmation does not alter past prefixes',()=>{const body=structure(bars.slice(0,7),2,'close','body');expect(body.blocks[0]).toMatchObject({lower:'100.00000000',upper:'100.50000000'});const later=bars.map((b,i)=>i>6?{...b,close:'99999',high:'99999'}:b);expect(structure(later.slice(0,7),2)).toEqual(structure(bars.slice(0,7),2));});
it('HTF changes only at complete bucket close and never fills holes',()=>{const b=fixture().bars;expect(completeBuckets(b.slice(0,23),STEP,24*STEP)).toHaveLength(0);expect(completeBuckets(b.slice(0,24),STEP,24*STEP)).toHaveLength(1);expect(completeBuckets(b.slice(0,24).filter((_,i)=>i!==8),STEP,24*STEP)).toHaveLength(0);const ctx={bars:b,i:240,timeframe_ms:STEP},a=htfStructure(ctx);expect(htfStructure({...ctx,bars:b.map((v,i)=>i>240?{...v,high:'NaN'}:v)})).toEqual(a);expect(a.as_of).toBe(b[239]!.close_time);});

it('protective fills retain trail/structure/breakeven rather than relabeling as initial stop',async()=>{const {SpotLedger}=await import('../../../src/demo/research/ledger.js');const {params}=await import('./fixtures.js');for(const reason of ['trail','structure','breakeven'] as const){const l=new SpotLedger({...params().execution,fee_rate:'0',slippage_bps:'0'});l.pending={action:'enter',entry:{candidate_id:'x',stop:'90',target:'120',reason:'test'}};l.step({...fixture().bars[0]!,open:'100',high:'102',low:'99',close:'101'});l.position!.stop=10000000000n;l.position!.stop_reason=reason;l.step({...fixture().bars[1]!,open:'101',high:'102',low:'98',close:'99'});expect(l.trades[0]!.reason).toBe(reason);}});
